spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fincalc
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false